### ISSUE TITLE
Running cna.tl.association returns KeyError: 'connectivities'

### ISSUE THREAD

**Issue by mturchin20** [immunogenomics/cna#19]
Hello,

I am running a first trial run of CNA. I am trying to run 'cna.tl.association', and I am getting a somewhat ambiguous error:

```
>>> res = cna.tl.association(d2,                   #dataset
...             d2.samplem.disease_status2,                   #sample-level attribute of intest (case/control status)
...             covs=d2.samplem[['sex2']])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/domino/.local/lib/python3.10/site-packages/cna/tools/_association.py", line 152, in association
    nam(data, batches=batches, covs=covs, filter_samples=filter_samples,
  File "/home/domino/.local/lib/python3.10/site-packages/cna/tools/_nam.py", line 185, in nam
    NAM = _nam(data, nsteps=nsteps, show_progress=show_progress)
  File "/home/domino/.local/lib/python3.10/site-packages/cna/tools/_nam.py", line 62, in _nam
    for i, s in enumerate(diffuse_stepwise(data, S, maxnsteps=maxnsteps)):
  File "/home/domino/.local/lib/python3.10/site-packages/cna/tools/_nam.py", line 23, in diffuse_stepwise
    a = get_connectivity(data)
  File "/home/domino/.local/lib/python3.10/site-packages/cna/tools/_nam.py", line 17, in get_connectivity
    return data.obsp["connectivities"]
  File "/opt/tbio/domino_202212/binaries/python-3.10.6/lib/python3.10/site-packages/anndata/_core/aligned_mapping.py", line 148, in __getitem__
    return self._data[key]
KeyError: 'connectivities'
>>> ad.__version__
'0.8.0'
>>> np.__version__
'1.23.5'
>>> sc.__version__
'1.9.1'
```

Based on another github issue post (https://github.com/Teichlab/bbknn/issues/38), I think this might be a product of differing package versions. However, it looks like based on the package version you alter your code on ("0.7.2"), the right function is being called with data.obsp["connectivities"]. Do you have any suggestions on what might be causing this?

Thanks!

**Comment by rumker** [comment]
Hi @mturchin20, thank you for your interest in CNA! Have you already constructed the nearest-neighbor graph for your data object? This error suggests CNA is having trouble locating it. If you have already constructed the nearest-neighbor graph, could you run 'd2' and share what the output is? I'd be looking for a list of the elements stored in the MultiAnnData object.

**Comment by mturchin20** [comment]
Thanks for your quick response @rumker! Yes, you are right. My files were not prepared properly. My nearest-neighbor graph wasn't where it should have been. After fixing that the method is running to completion now. I'll close the issue.
