### ISSUE TITLE
Running cna.tl.nam returns LinAlgError: SVD did not converge

### ISSUE THREAD

**Issue by MiaoLab2024** [immunogenomics/cna#21]
Hello,

I am trying to run "cna.tl.nam", and I got an LinAlgError:

>>> sc.pp.neighbors(d)
>>> sc.tl.umap(d)
>>> cna.tl.nam(d, covs=d.samplem[['group']])
/home/.local/lib/python3.9/site-packages/cna/tools/_nam.py:112: RuntimeWarning: invalid value encountered in true_divide
  covs = (covs - covs.mean(axis=0))/covs.std(axis=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.local/lib/python3.9/site-packages/cna/tools/_nam.py", line 207, in nam
    U, svs, V = _svd_nam(NAM_resid)
  File "/home/.local/lib/python3.9/site-packages/cna/tools/_nam.py", line 148, in _svd_nam
    U, svs, UT = np.linalg.svd(NAM.dot(NAM.T))
  File "<__array_function__ internals>", line 5, in svd
  File "/mnt/data/R4.1_and_Rstudio/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 1660, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "/mnt/data/R4.1_and_Rstudio/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 97, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge

>>> sc.__version__
'1.7.2'
>>> np.__version__
'1.21.0'
>>> ad.__version__
'0.8.0'

I extract the T cell subset to run "cna.tl.nam", and the total count is 22,176. Our grouping is set from 0 to 4 . As this issue has not been previously discussed,  could you give any suggestions on what might be causing this?
Thanks!

**Comment by MiaoLab2024** [comment]
@rumker Thank you very much.  "cna.tl.nam(d, batches=d.samplem[['group']] )" works well. However, when plotting the neighborhood loadings of NAM PC1, the shape of the cluster looks weird. Since I'm an R user,  I applied the procedure mentioned in 'rcna' to process the scRNA-seq data (including finding variable genes, scaling data, running PCA, harmonizing over donor ID and running UMAP). Then I tranformed the pre-analyzed Seurat object into anndata format, and performed "cna.tl.nam" in python.  I am wondering if there might be an issue with the data format or if the transformation process was not executed correctly.  
Thanks againt!
![1732109276625](https://github.com/user-attachments/assets/1f6950c0-ed14-42e4-a978-b7929711ba8f)

**Comment by rumker** [comment]
Great @MiaoLab2024, if those 'groups' are your batches then supplying the 'groups' variable to the `batches` parameter is preferable to what I described above. 

If you're more comfortable doing the initial data processing in R, you could consider transitioning to python just before the step of nearest neighbor graph construction. In other words, you could export your cells-by-PCs matrix from R, add that matrix to an (empty) anndata object `d` along with your sample metadata table and when you call scanpy.pp.neighbors() on `d` you can use the `use_rep` parameter to point scanpy to your cells-by-PCs matrix to use as the basis for the nearest neighbor graph. (You could also define your UMAP in R and export the UMAP1 and UMAP 2 loadings per cell to store in the anndata object at `d.obsm['X_umap']` if you like.)
