### ISSUE TITLE
Error in SeuratObject imported data

### ISSUE THREAD

**Issue by ttab963** [immunogenomics/cna#9]
Hi. Thanks for chance to use your amazing tool.

But I have some problems. I have SeuratObject which contains about 3,000 cells.
So I just transport this data by changing to .h5ad file and function in scanpy (e.g. drawing umap plot...) works well.
However when i try to use `cna.tl.association()`, some errors pop out.

~~~
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scanpy as sc
import cna
import anndata as ad
from multianndata import MultiAnnData

d = ad.read_h5ad('/data/users/sjp/Projects/scHCC/Non_Imm.cut.h5ad')
d = MultiAnnData(d)
d.obs_to_sample(['HBV_RNA_num', 'sample', 'cov'])

res = cna.tl.association(d, d.samplem.HBV_RNA_num, covs=d.samplem[['cov']], batch=d.samplem.sample )  
~~~
and this error happend.
~~~
qcd NAM not found; computing and saving
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/anaconda3/lib/python3.8/site-packages/cna/tools/_association.py", line 137, in association
    nam(data, batches=batches, covs=covs, filter_samples=filter_samples,
  File "/data/anaconda3/lib/python3.8/site-packages/cna/tools/_nam.py", line 163, in nam
    NAM = _nam(data, nsteps=nsteps)
  File "/data/anaconda3/lib/python3.8/site-packages/cna/tools/_nam.py", line 47, in _nam
    for i, s in enumerate(diffuse_stepwise(data, s, maxnsteps=maxnsteps)):
  File "/data/anaconda3/lib/python3.8/site-packages/cna/tools/_nam.py", line 16, in diffuse_stepwise
    a = data.obsp["distances"]
  File "/data/anaconda3/lib/python3.8/site-packages/anndata/_core/aligned_mapping.py", line 148, in __getitem__
    return self._data[key]
KeyError: 'distances'
~~~

Also i write down my info,.
~~~
sc.logging.print_header()
~~~
~~~
scanpy==1.8.1 anndata==0.7.6 umap==0.5.1 numpy==1.20.3 scipy==1.7.2 pandas==1.3.4 scikit-learn==0.22 statsmodels==0.13.1 pynndescent==0.5.4
~~~

~~~
d.samplem
~~~
~~~
      HBV_RNA_num  sample  cov
id
0             1.0     1.0  0.0
1             1.0     1.0  0.0
2             0.0     4.0  0.0
3             0.0     4.0  0.0
4             0.0     4.0  0.0
...           ...     ...  ...
3040          0.0    45.0  0.0
3041          0.0    45.0  0.0
3042          0.0    45.0  0.0
3043          0.0    46.0  0.0
3044          0.0    46.0  0.0
~~~

If you need any other informations, please reply for that.

Thanks so much.

**Comment by yakirr** [comment]
Thanks for the kind words and for your interest in CNA! It looks from what you've written like CNA is unable to find a nearest neighbor graph in your data object. Could it be that the way you're importing the object into scanpy is preserving the umap coordinates but "throwing away" the nearest neighbor graph information? (You can generate this in scanpy using the [neighbors](https://scanpy.readthedocs.io/en/stable/generated/scanpy.pp.neighbors.html) function)

**Comment by ttab963** [comment]
Thanks a lot to kind answer.

I changed my code like this.
~~~
d = ad.read_h5ad('/data/users/sjp/Projects/scHCC/Non_Imm.cut.h5ad')
d = MultiAnnData(d)
d.obs_to_sample(['HBV_RNA_num', 'sex', 'cov'])

sc.pp.neighbors(d, n_pcs = 20, use_rep = 'X_harmony')

res = cna.tl.association(d,                
            d.samplem.HBV_RNA_num,
            covs=d.samplem[['cov']],
            batch=d.samplem.sex )       
print('\nglobal association p-value:', res.p)
~~~
It works better, but another error comes out.
~~~
qcd NAM not found; computing and saving
        taking step 1
        median kurtosis: 833.3524588650529
        taking step 2
        median kurtosis: 432.1254750641751
        taking step 3
        median kurtosis: 250.00493380360746
        taking step 4
        median kurtosis: 189.38057819059614
        taking step 5
        median kurtosis: 155.64395125514596
        taking step 6
        median kurtosis: 145.52952402761073
        taking step 7
        median kurtosis: 141.75798917845793
        taking step 8
        median kurtosis: 143.9309340065955
stopping after 8 steps
/usr/local/lib/python3.8/dist-packages/cna/tools/_nam.py:71: UserWarning: only one unique batch supplied to qc
  warnings.warn('only one unique batch supplied to qc')
covariate-adjusted NAM not found; computing and saving
/usr/local/lib/python3.8/dist-packages/cna/tools/_nam.py:90: RuntimeWarning: invalid value encountered in true_divide
  covs = (covs - covs.mean(axis=0))/covs.std(axis=0)
/usr/local/lib/python3.8/dist-packages/cna/tools/_nam.py:93: UserWarning: only one unique batch supplied to prep
  warnings.warn('only one unique batch supplied to prep')
computing SVD
~~~
I think the batch by 'sample' is problem first, but this error pop again after i change batch or not using harmony.

Thanks again, @yakirr .

**Comment by rumker** [comment]
Hi there, thank you for your interest in CNA! It looks in this most recent set of code blocks as though you are supplying d.samplem.sex to the association function as the batch values per sample.  Is it possible that vector has the same value across all samples, prompting the error 'only one unique batch supplied to prep'? If you do have one sample per batch, we'd advise running CNA with the 'batch' parameter set to None. (And pursuing batch correction as a dataset pre-processing step, e.g. through Harmony). Let us know if that works or if we can assist you further!
